apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  labels:
    cluster: k8s.kaas
spec:
  baseImage: cassandra
  version: latest
  configMapName: cassandra-configmap-v1
  dataCapacity: "200Mi"
  dataStorageClass: "local-path"
  imagepullpolicy: IfNotPresent
  hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 999
  resources:
    requests:
      cpu: '{{ k8s_cassandracluster_cpu_request }}'
      memory: {{ k8s_cassandracluster_memory_request }}
    limits:
      cpu: '{{ k8s_cassandracluster_cpu_limit }}'
      memory: {{ k8s_cassandracluster_memory_limit }}
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        rack:
          - name: rack1
          - name: rack2
          - name: rack3
